### ISSUE TITLE
python-pcl lib

### ISSUE THREAD

**Issue by sfornengo** [lpltk/pydriver#1]
Could it be possible to use/update python-pcl lib instead of developing your own binding ?

**Comment by Leonard-Plotkin** [comment]
I looked into it before developing PyDriver, but it didn't look like a feasible way. There are fundamental problems in developing universal bindings between dynamically typed languages like Python and libraries which heavily depend on static typing like PCL. Developing my own specialized bindings for combinations of parameter types used by PyDriver seemed to be the only viable option for me. Additionally, some of the functions combine multiple operations to avoid performance penalties, hence the narrow specialization which would be questionable in a project targeting universal PCL bindings.

**Comment by sfornengo** [comment]
Thanks for this interesting explanations.

**Comment by Leonard-Plotkin** [comment]
You're welcome, thank you for your feedback!
