### ISSUE TITLE
Keypoint extraction

### ISSUE THREAD

**Issue by bored-wolf** [lpltk/pydriver#7]
Since the keypoints extracted from a pointcloud using the PCLhelper instance (ISS or Harris) are stored as a class of that instance, would it be possible to extract them to a numpy array?

**Comment by Leonard-Plotkin** [comment]
Yes, the function PCLHelper.toArray() should do the trick. See also:
https://github.com/lpltk/pydriver/blob/master/pydriver/pcl/pcl.pyx#L214

**Comment by bored-wolf** [comment]
Yup, that worked! Thank you so much.
